### ISSUE TITLE
WebView broken

### ISSUE THREAD

**Issue by zgfg** [TheHitMan7/Magisk-Files#1]
Could you update with the WebView fix

Two weeks ago or so, initial vvb2060 Alpha release with Zygisk also had broken WebView but later was fixed

Otherwise, nice to have the Repo and MagiskHide

Btw, do you have a Telegram channel or some forum - thanks

**Comment by TheHitMan7** [comment]
Hi,

Apologize for the delay, will release a new magisk build soon. BTW i never have webview crash here.

Channel [@magiskcustom](https://t.me/magiskcustom)
Support Group [@custommagisk](https://t.me/custommagisk)
