### ISSUE TITLE
Magisk Hide can't enabled

### ISSUE THREAD

**Issue by skelletR** [TheHitMan7/Magisk-Files#2]
Latest Bluestacks, fresh install with your magisk, go to setting to enable Magisk Hide but Magisk Hide can't enabled
![Στιγμιότυπο οθόνης (323)](https://user-images.githubusercontent.com/25982450/158229989-b3b21be0-1ce8-48ab-b6dc-a7303ab4b8bc.png)

**Comment by TheHitMan7** [comment]
MagiskHide now needs Zygisk Enabled.

**Comment by skelletR** [comment]
> MagiskHide now needs Zygisk Enabled.
> 
> There will be a proper fix for the same in next stable release.

Oh, understand, because zygisk is not work in bluestacks emulator
