### ISSUE TITLE
BlueStacks

### ISSUE THREAD

**Issue by skelletR** [TheHitMan7/Magisk-Files#3]
Hi, the new version, magisk hide need zygisk enabled, but in the BlueStacks zygisk not working and only riru and riru module works, how enabled magisk hide without zygisk?

**Comment by TheHitMan7** [comment]
I will fix this in new update.

@skelletR

**Comment by skelletR** [comment]
> I will fix this in new update.
> 
> @skelletR

Thank you

**Comment by HuskyDG** [comment]
> > I will fix this in new update.
> > @skelletR
> 
> Thank you

https://github.com/HuskyDG/magisk-files

**Comment by HuskyDG** [comment]
Bluestacks Android 9 only riru v25 will work. I recommended you to use NoxPlayer or MumuGlobal Android 9.

**Comment by skelletR** [comment]
> Bluestacks Android 9 only riru v25 will work. I recommended you to use NoxPlayer or MumuGlobal Android 9.

Yeah I know, because I want and hide for that, now I have the older version 24102 of your magisk on BlueStacks to enable magiskhide
